name: Python package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9, 3.10.0]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements-test.txt
    - name: Check with isort
      run: |
        isort brother tests --check-only
    - name: Check with Black Code Formatter
      run: |
        black brother tests --check
    - name: Lint with flake8
      run: |
        flake8 brother tests
    - name: Lint with pylint
      run: |
        pylint brother tests
    - name: Test with mypy
      run: |
        mypy brother
    - name: Test with pytest
      run: |
        python setup.py test
